# -*- coding: utf-8 -*-
"""Enhanced Manufacturing Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REO1QLjS5uXnzrxMErwNe2uCFDm3zR-A
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
import io

def run_advanced_thales_analysis(df):
    """
    Enhanced analysis suite for Thales Group Manufacturing data.
    Focuses on 6G Latency vs Machine Health and Predictive Maintenance.
    """
    print("--- Thales Advanced Intelligence Report ---")

    # 1. Feature Engineering: Health Index
    # Combining physical sensors and network stability
    df['Composite_Risk_Score'] = (
        (df['Temperature_C'] / 100) * 0.3 +
        (df['Vibration_Hz'] / 5) * 0.3 +
        (df['Network_Latency_ms'] / 50) * 0.2 +
        (1 - df['Predictive_Maintenance_Score']) * 0.2
    )

    # 2. Visualizing Network impact on Errors
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    sns.regplot(data=df.sample(2000), x='Network_Latency_ms', y='Error_Rate_%',
                scatter_kws={'alpha':0.3}, line_kws={'color':'red'})
    plt.title('6G Latency vs Error Rate Impact')

    plt.subplot(1, 2, 2)
    sns.boxplot(data=df, x='Efficiency_Status', y='Predictive_Maintenance_Score', palette='viridis')
    plt.title('Maintenance Score by Efficiency Class')
    plt.tight_layout()
    plt.show()

    # 3. High-Risk Heatmap (Temperature vs Vibration)
    plt.figure(figsize=(10, 6))
    pivot_table = df.sample(5000).pivot_table(
        values='Composite_Risk_Score',
        index=pd.cut(df['Temperature_C'], bins=10),
        columns=pd.cut(df['Vibration_Hz'], bins=10)
    )
    sns.heatmap(pivot_table, cmap='YlOrRd', annot=False)
    plt.title('Mechanical Risk Heatmap: Temp vs Vibration')
    plt.xlabel('Vibration (Hz)')
    plt.ylabel('Temperature (C)')
    plt.show()

    # 4. Critical Asset Summary
    critical_assets = df[df['Predictive_Maintenance_Score'] < 0.2]
    top_problem_machines = critical_assets['Machine_ID'].value_counts().head(5)

    print(f"\nTotal Records: {len(df)}")
    print(f"Total Anomalies Identified: {len(critical_assets)}")
    print("\nTop 5 Machines Requiring Immediate Service:")
    for m_id, count in top_problem_machines.items():
        avg_temp = df[df['Machine_ID'] == m_id]['Temperature_C'].mean()
        print(f" - Machine {m_id}: {count} critical events (Avg Temp: {avg_temp:.1f}°C)")

# --- Execution for Colab ---
# If you already have 'df' from your previous upload, just run:
# run_advanced_thales_analysis(df)

# Or upload fresh:
print("Upload your 'Thales_Group_Manufacturing (1).csv' file:")
uploaded = files.upload()
if uploaded:
    file_name = list(uploaded.keys())[0]
    df_thales = pd.read_csv(io.BytesIO(uploaded[file_name]))
    run_advanced_thales_analysis(df_thales)